"""add firmware_version to defects

Revision ID: 5a77af9c583e
Revises: b80fb4424175
Create Date: 2026-01-20 00:25:35.043765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a77af9c583e'
down_revision: Union[str, Sequence[str], None] = 'b80fb4424175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defects', sa.Column('firmware_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defects', 'firmware_version')
    # ### end Alembic commands ###
