"""add firmware_version and options to machines

Revision ID: b80fb4424175
Revises: dd7c1c195e31
Create Date: 2026-01-20 00:16:47.993201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80fb4424175'
down_revision: Union[str, Sequence[str], None] = 'dd7c1c195e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('firmware_version', sa.String(length=20), nullable=True))
    op.add_column('machines', sa.Column('options', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'options')
    op.drop_column('machines', 'firmware_version')
    # ### end Alembic commands ###
