"""Initial tables

Revision ID: d3c8e7384f7a
Revises: 
Create Date: 2026-01-17 20:35:25.623139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c8e7384f7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=50), nullable=False),
    sa.Column('manufacture_month', sa.String(length=7), nullable=False),
    sa.Column('operation_start_month', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_event_date'), 'annotations', ['event_date'], unique=False)
    op.create_index(op.f('ix_annotations_machine_id'), 'annotations', ['machine_id'], unique=False)
    op.create_table('machine_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('characteristic_id', sa.String(length=50), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('aggregation', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_data_characteristic_id'), 'machine_data', ['characteristic_id'], unique=False)
    op.create_index(op.f('ix_machine_data_machine_id'), 'machine_data', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_data_month'), 'machine_data', ['month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_data_month'), table_name='machine_data')
    op.drop_index(op.f('ix_machine_data_machine_id'), table_name='machine_data')
    op.drop_index(op.f('ix_machine_data_characteristic_id'), table_name='machine_data')
    op.drop_table('machine_data')
    op.drop_index(op.f('ix_annotations_machine_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_event_date'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_table('machines')
    op.drop_table('models')
    op.drop_table('characteristics')
    op.drop_table('series')
    op.drop_table('categories')
    op.drop_table('aggregations')
    # ### end Alembic commands ###
